// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp1eXTBb5b8zY8kVeYs3BoxMwHwZ-gcgU',
    appId: '1:701324178164:web:01ea2c089a8d9e5ae264a1',
    messagingSenderId: '701324178164',
    projectId: 'unitalk-c171e',
    authDomain: 'unitalk-c171e.firebaseapp.com',
    storageBucket: 'unitalk-c171e.appspot.com',
    measurementId: 'G-HTKPRYMWP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByeJZN-GzOUqZl2aRjB8SxDLLU6PR79B8',
    appId: '1:701324178164:android:d3ff7099d9e1b188e264a1',
    messagingSenderId: '701324178164',
    projectId: 'unitalk-c171e',
    storageBucket: 'unitalk-c171e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoXh_I4QmsydX5B7jcZ06u3TXcUdNV-bI',
    appId: '1:701324178164:ios:fbc00fa304023e14e264a1',
    messagingSenderId: '701324178164',
    projectId: 'unitalk-c171e',
    storageBucket: 'unitalk-c171e.appspot.com',
    iosClientId: '701324178164-o801l0h227b8mouni266u05bc6b9re90.apps.googleusercontent.com',
    iosBundleId: 'com.uniteam.uniTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoXh_I4QmsydX5B7jcZ06u3TXcUdNV-bI',
    appId: '1:701324178164:ios:fbc00fa304023e14e264a1',
    messagingSenderId: '701324178164',
    projectId: 'unitalk-c171e',
    storageBucket: 'unitalk-c171e.appspot.com',
    iosClientId: '701324178164-o801l0h227b8mouni266u05bc6b9re90.apps.googleusercontent.com',
    iosBundleId: 'com.uniteam.uniTalk',
  );
}
